### ISSUE TITLE
Change vendor

### ISSUE THREAD

**Issue by bashmach** [joecohens/laravel-elixir-requirejs#10]
It seems current vendor `gulp-requirejs` is outdated and not supported (8 open issues and 11 open pull requests).
And what is more important - it seems it doesn't provide a stable support for `gulp watch`. Have you ever tried to run this command on your projects? I'm getting an error on the second file change.

I assume to use `gulp-requirejs-optimize` instead. It looks like a stable and covered by tests package. And it supports `gulp watch` :smile: 

Is there any specific cases which we need to test and provide backward compatibility?

**Comment by joecohens** [comment]
Didn't know about it existence haha. By reading the docs it seems to be only a nice replacement! If outputs and dirs are the same I think we are more than fine to replace it :smile:
