### ISSUE TITLE
Plugin only outputs a blank define

### ISSUE THREAD

**Issue by mseymour** [joecohens/laravel-elixir-requirejs#13]
I must be doing something wrong, since nothing in my app.js file (which is what I use for my main javascript file) seem to change the output, which is plainly `define("app", function() {});`.

The current contents of my app.js is currently only `requirejs(['/node_modules/bootstrap/dist/bootstrap']);`.

**Comment by mortennajbjerg** [comment]
Any chance You could tell us more about the solution You found? I'm facing a similar problem.
